---
deployment:
  tasks:
    - export DEPLOYPATH=/home/siliconnorth/public_html/
    - /bin/cp ./home.html $DEPLOYPATH
    - /bin/cp ./background.png $DEPLOYPATH
    - /bin/cp ./alert.png $DEPLOYPATH
